// Generated by gencpp from file webots_drive/ContactPoint.msg
// DO NOT EDIT!


#ifndef WEBOTS_DRIVE_MESSAGE_CONTACTPOINT_H
#define WEBOTS_DRIVE_MESSAGE_CONTACTPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace webots_drive
{
template <class ContainerAllocator>
struct ContactPoint_
{
  typedef ContactPoint_<ContainerAllocator> Type;

  ContactPoint_()
    : point()
    , node_id(0)  {
    }
  ContactPoint_(const ContainerAllocator& _alloc)
    : point(_alloc)
    , node_id(0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _point_type;
  _point_type point;

   typedef int32_t _node_id_type;
  _node_id_type node_id;





  typedef boost::shared_ptr< ::webots_drive::ContactPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::webots_drive::ContactPoint_<ContainerAllocator> const> ConstPtr;

}; // struct ContactPoint_

typedef ::webots_drive::ContactPoint_<std::allocator<void> > ContactPoint;

typedef boost::shared_ptr< ::webots_drive::ContactPoint > ContactPointPtr;
typedef boost::shared_ptr< ::webots_drive::ContactPoint const> ContactPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::webots_drive::ContactPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::webots_drive::ContactPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::webots_drive::ContactPoint_<ContainerAllocator1> & lhs, const ::webots_drive::ContactPoint_<ContainerAllocator2> & rhs)
{
  return lhs.point == rhs.point &&
    lhs.node_id == rhs.node_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::webots_drive::ContactPoint_<ContainerAllocator1> & lhs, const ::webots_drive::ContactPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace webots_drive

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::webots_drive::ContactPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::webots_drive::ContactPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::webots_drive::ContactPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::webots_drive::ContactPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webots_drive::ContactPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webots_drive::ContactPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::webots_drive::ContactPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c401f69a1503004a9e4aec8ae5ec3e17";
  }

  static const char* value(const ::webots_drive::ContactPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc401f69a1503004aULL;
  static const uint64_t static_value2 = 0x9e4aec8ae5ec3e17ULL;
};

template<class ContainerAllocator>
struct DataType< ::webots_drive::ContactPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "webots_drive/ContactPoint";
  }

  static const char* value(const ::webots_drive::ContactPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::webots_drive::ContactPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point point\n"
"int32 node_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::webots_drive::ContactPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::webots_drive::ContactPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.point);
      stream.next(m.node_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ContactPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::webots_drive::ContactPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::webots_drive::ContactPoint_<ContainerAllocator>& v)
  {
    s << indent << "point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
    s << indent << "node_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.node_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEBOTS_DRIVE_MESSAGE_CONTACTPOINT_H
