// Generated by gencpp from file webots_drive/node_set_visibility.msg
// DO NOT EDIT!


#ifndef WEBOTS_DRIVE_MESSAGE_NODE_SET_VISIBILITY_H
#define WEBOTS_DRIVE_MESSAGE_NODE_SET_VISIBILITY_H

#include <ros/service_traits.h>


#include <webots_drive/node_set_visibilityRequest.h>
#include <webots_drive/node_set_visibilityResponse.h>


namespace webots_drive
{

struct node_set_visibility
{

typedef node_set_visibilityRequest Request;
typedef node_set_visibilityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_set_visibility
} // namespace webots_drive


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webots_drive::node_set_visibility > {
  static const char* value()
  {
    return "b6fcfa2c79ae79467e085318b3617289";
  }

  static const char* value(const ::webots_drive::node_set_visibility&) { return value(); }
};

template<>
struct DataType< ::webots_drive::node_set_visibility > {
  static const char* value()
  {
    return "webots_drive/node_set_visibility";
  }

  static const char* value(const ::webots_drive::node_set_visibility&) { return value(); }
};


// service_traits::MD5Sum< ::webots_drive::node_set_visibilityRequest> should match
// service_traits::MD5Sum< ::webots_drive::node_set_visibility >
template<>
struct MD5Sum< ::webots_drive::node_set_visibilityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webots_drive::node_set_visibility >::value();
  }
  static const char* value(const ::webots_drive::node_set_visibilityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_drive::node_set_visibilityRequest> should match
// service_traits::DataType< ::webots_drive::node_set_visibility >
template<>
struct DataType< ::webots_drive::node_set_visibilityRequest>
{
  static const char* value()
  {
    return DataType< ::webots_drive::node_set_visibility >::value();
  }
  static const char* value(const ::webots_drive::node_set_visibilityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webots_drive::node_set_visibilityResponse> should match
// service_traits::MD5Sum< ::webots_drive::node_set_visibility >
template<>
struct MD5Sum< ::webots_drive::node_set_visibilityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webots_drive::node_set_visibility >::value();
  }
  static const char* value(const ::webots_drive::node_set_visibilityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_drive::node_set_visibilityResponse> should match
// service_traits::DataType< ::webots_drive::node_set_visibility >
template<>
struct DataType< ::webots_drive::node_set_visibilityResponse>
{
  static const char* value()
  {
    return DataType< ::webots_drive::node_set_visibility >::value();
  }
  static const char* value(const ::webots_drive::node_set_visibilityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBOTS_DRIVE_MESSAGE_NODE_SET_VISIBILITY_H
