// Generated by gencpp from file webots_drive/set_string.msg
// DO NOT EDIT!


#ifndef WEBOTS_DRIVE_MESSAGE_SET_STRING_H
#define WEBOTS_DRIVE_MESSAGE_SET_STRING_H

#include <ros/service_traits.h>


#include <webots_drive/set_stringRequest.h>
#include <webots_drive/set_stringResponse.h>


namespace webots_drive
{

struct set_string
{

typedef set_stringRequest Request;
typedef set_stringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_string
} // namespace webots_drive


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webots_drive::set_string > {
  static const char* value()
  {
    return "0462bc0e878964615c49ad8ef45df667";
  }

  static const char* value(const ::webots_drive::set_string&) { return value(); }
};

template<>
struct DataType< ::webots_drive::set_string > {
  static const char* value()
  {
    return "webots_drive/set_string";
  }

  static const char* value(const ::webots_drive::set_string&) { return value(); }
};


// service_traits::MD5Sum< ::webots_drive::set_stringRequest> should match
// service_traits::MD5Sum< ::webots_drive::set_string >
template<>
struct MD5Sum< ::webots_drive::set_stringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webots_drive::set_string >::value();
  }
  static const char* value(const ::webots_drive::set_stringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_drive::set_stringRequest> should match
// service_traits::DataType< ::webots_drive::set_string >
template<>
struct DataType< ::webots_drive::set_stringRequest>
{
  static const char* value()
  {
    return DataType< ::webots_drive::set_string >::value();
  }
  static const char* value(const ::webots_drive::set_stringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webots_drive::set_stringResponse> should match
// service_traits::MD5Sum< ::webots_drive::set_string >
template<>
struct MD5Sum< ::webots_drive::set_stringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webots_drive::set_string >::value();
  }
  static const char* value(const ::webots_drive::set_stringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_drive::set_stringResponse> should match
// service_traits::DataType< ::webots_drive::set_string >
template<>
struct DataType< ::webots_drive::set_stringResponse>
{
  static const char* value()
  {
    return DataType< ::webots_drive::set_string >::value();
  }
  static const char* value(const ::webots_drive::set_stringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBOTS_DRIVE_MESSAGE_SET_STRING_H
