// Generated by gencpp from file webots_drive/set_bool.msg
// DO NOT EDIT!


#ifndef WEBOTS_DRIVE_MESSAGE_SET_BOOL_H
#define WEBOTS_DRIVE_MESSAGE_SET_BOOL_H

#include <ros/service_traits.h>


#include <webots_drive/set_boolRequest.h>
#include <webots_drive/set_boolResponse.h>


namespace webots_drive
{

struct set_bool
{

typedef set_boolRequest Request;
typedef set_boolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_bool
} // namespace webots_drive


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webots_drive::set_bool > {
  static const char* value()
  {
    return "24a0f9fd764459b7e35d04a0dd83dd11";
  }

  static const char* value(const ::webots_drive::set_bool&) { return value(); }
};

template<>
struct DataType< ::webots_drive::set_bool > {
  static const char* value()
  {
    return "webots_drive/set_bool";
  }

  static const char* value(const ::webots_drive::set_bool&) { return value(); }
};


// service_traits::MD5Sum< ::webots_drive::set_boolRequest> should match
// service_traits::MD5Sum< ::webots_drive::set_bool >
template<>
struct MD5Sum< ::webots_drive::set_boolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webots_drive::set_bool >::value();
  }
  static const char* value(const ::webots_drive::set_boolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_drive::set_boolRequest> should match
// service_traits::DataType< ::webots_drive::set_bool >
template<>
struct DataType< ::webots_drive::set_boolRequest>
{
  static const char* value()
  {
    return DataType< ::webots_drive::set_bool >::value();
  }
  static const char* value(const ::webots_drive::set_boolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webots_drive::set_boolResponse> should match
// service_traits::MD5Sum< ::webots_drive::set_bool >
template<>
struct MD5Sum< ::webots_drive::set_boolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webots_drive::set_bool >::value();
  }
  static const char* value(const ::webots_drive::set_boolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_drive::set_boolResponse> should match
// service_traits::DataType< ::webots_drive::set_bool >
template<>
struct DataType< ::webots_drive::set_boolResponse>
{
  static const char* value()
  {
    return DataType< ::webots_drive::set_bool >::value();
  }
  static const char* value(const ::webots_drive::set_boolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBOTS_DRIVE_MESSAGE_SET_BOOL_H
