// Generated by gencpp from file webots_drive/supervisor_get_from_string.msg
// DO NOT EDIT!


#ifndef WEBOTS_DRIVE_MESSAGE_SUPERVISOR_GET_FROM_STRING_H
#define WEBOTS_DRIVE_MESSAGE_SUPERVISOR_GET_FROM_STRING_H

#include <ros/service_traits.h>


#include <webots_drive/supervisor_get_from_stringRequest.h>
#include <webots_drive/supervisor_get_from_stringResponse.h>


namespace webots_drive
{

struct supervisor_get_from_string
{

typedef supervisor_get_from_stringRequest Request;
typedef supervisor_get_from_stringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct supervisor_get_from_string
} // namespace webots_drive


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webots_drive::supervisor_get_from_string > {
  static const char* value()
  {
    return "fcb5d4f10a46a1a9f10528733a3b9b3a";
  }

  static const char* value(const ::webots_drive::supervisor_get_from_string&) { return value(); }
};

template<>
struct DataType< ::webots_drive::supervisor_get_from_string > {
  static const char* value()
  {
    return "webots_drive/supervisor_get_from_string";
  }

  static const char* value(const ::webots_drive::supervisor_get_from_string&) { return value(); }
};


// service_traits::MD5Sum< ::webots_drive::supervisor_get_from_stringRequest> should match
// service_traits::MD5Sum< ::webots_drive::supervisor_get_from_string >
template<>
struct MD5Sum< ::webots_drive::supervisor_get_from_stringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webots_drive::supervisor_get_from_string >::value();
  }
  static const char* value(const ::webots_drive::supervisor_get_from_stringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_drive::supervisor_get_from_stringRequest> should match
// service_traits::DataType< ::webots_drive::supervisor_get_from_string >
template<>
struct DataType< ::webots_drive::supervisor_get_from_stringRequest>
{
  static const char* value()
  {
    return DataType< ::webots_drive::supervisor_get_from_string >::value();
  }
  static const char* value(const ::webots_drive::supervisor_get_from_stringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webots_drive::supervisor_get_from_stringResponse> should match
// service_traits::MD5Sum< ::webots_drive::supervisor_get_from_string >
template<>
struct MD5Sum< ::webots_drive::supervisor_get_from_stringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webots_drive::supervisor_get_from_string >::value();
  }
  static const char* value(const ::webots_drive::supervisor_get_from_stringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_drive::supervisor_get_from_stringResponse> should match
// service_traits::DataType< ::webots_drive::supervisor_get_from_string >
template<>
struct DataType< ::webots_drive::supervisor_get_from_stringResponse>
{
  static const char* value()
  {
    return DataType< ::webots_drive::supervisor_get_from_string >::value();
  }
  static const char* value(const ::webots_drive::supervisor_get_from_stringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBOTS_DRIVE_MESSAGE_SUPERVISOR_GET_FROM_STRING_H
