controller_list:
  - name: nao_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - LWristYaw
      - RShoulderPitch
      - RShoulderRoll
      - RElbowYaw
      - RElbowRoll
      - RWristYaw
      - HeadYaw
      - HeadPitch
      - LHipPitch
      - LKneePitch
      - LAnklePitch
      - LAnkleRoll
      - RHipPitch
      - RKneePitch
      - RAnklePitch
      - RAnkleRoll
      - LHand
      - RHand
      - LShoulderPitch
      - LShoulderRoll
      - LElbowYaw
      - LElbowRoll
      - LWristYaw
      - RShoulderPitch
      - RShoulderRoll
      - RElbowYaw
      - RElbowRoll
      - RWristYaw